import {useState,useEffect} from 'react';
import {Cloud,LayoutDashboard,FolderKanban,ListTodo,Users,Server,ChartNoAxesCombined,ArrowUpRight,ArrowRight,Plus,Search,Check,Activity,ChevronDown,Clock,Layers,BookOpen,FileText} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import ProjectGantt from './project-gantt';
import {validateDates} from '@/lib/gantt.mjs';
import {Progress} from '@/components/ui/progress';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {addItem,completeTask,filterItems,projectTasks,updateItem} from '@/lib/workspace.mjs';
const initialProjects=[{id:'1',name:'Cloud infrastructure migration',description:'A stronger foundation for what’s next.',status:'On track',progress:72,team:'Platform',due:'Sep 18',color:'purple'},{id:'2',name:'Developer experience',description:'Making every deployment feel effortless.',status:'On track',progress:48,team:'Engineering',due:'Sep 24',color:'blue'},{id:'3',name:'Observability rollout',description:'Clarity across every service and signal.',status:'At risk',progress:35,team:'DevOps',due:'Sep 12',color:'orange'}];
const initialTasks=[{id:'1',projectId:'1',start:'2026-09-01',phase:'Planning',date:'2026-09-07',name:'Review production deployment pipeline',status:'In progress',priority:'High',owner:'Alex Morgan',due:'2026-09-07'},{id:'2',projectId:'1',start:'2026-09-08',phase:'Development',date:'2026-09-12',name:'Configure staging environment',status:'To do',priority:'Medium',owner:'Sarah Chen',due:'2026-09-12'},{id:'3',projectId:'2',start:'2026-09-03',phase:'Development',date:'2026-09-10',name:'Update infrastructure documentation',status:'In progress',priority:'Medium',owner:'James Wilson',due:'2026-09-10'},{id:'4',projectId:'3',start:'2026-09-05',phase:'Planning',date:'2026-09-12',name:'Audit unused cloud resources',status:'To do',priority:'High',owner:'Priya Patel',due:'2026-09-12'}];
const members=[['Alex Morgan','Platform Lead','AM',78],['Sarah Chen','Cloud Engineer','SC',64],['James Wilson','DevOps Engineer','JW',91],['Priya Patel','SRE','PP',56]] as const;
const resources=[['production-api','AWS','Compute','Healthy','$842'],['analytics-cluster','Google Cloud','Database','Healthy','$628'],['staging-services','AWS','Compute','Healthy','$316'],['asset-storage','Azure','Storage','Review needed','$214']];
const nav=[['Overview',LayoutDashboard],['Projects',FolderKanban],['Tasks',ListTodo],['Knowledge',BookOpen],['Team',Users],['Cloud resources',Server],['Reports',ChartNoAxesCombined]] as const;
const initialKnowledge=[
{id:'k1',name:'Production deployment checklist',category:'Runbooks',body:'Before you deploy\n\n1. Confirm the change has passed review and automated checks.\n2. Check the service dashboard and active incidents.\n3. Record the previous release and rollback procedure.\n4. Deploy to staging and verify the critical user journeys.\n5. Schedule the production change with the on-call engineer.\n\nAfter deployment\n\nWatch error rates and latency. Record the result and hand over any follow-up work.',author:'Alex Morgan'},
{id:'k2',name:'Welcome to the cloud team',category:'Onboarding',body:'Your first week\n\nMeet your buddy and review the team directory. Get familiar with our active projects, weekly priorities and service ownership.\n\nStart with a small task, review the relevant runbook and ask your buddy to walk you through the deployment workflow.\n\nKeep useful discoveries here so the next person can find them.',author:'Sarah Chen'},
{id:'k3',name:'Cloud resource naming convention',category:'Guides',body:'Use a consistent name for each resource:\n\nteam-service-environment-region\n\nExample: platform-api-staging-us-east\n\nInclude an owner, environment and project tag. Keep descriptions clear and avoid storing credentials in names or tags.',author:'James Wilson'},
{id:'k4',name:'Weekly platform review · September 7',category:'Meeting notes',body:'Focus this week\n\n• Complete the staging environment setup.\n• Review the migration readiness checklist.\n• Identify unused resources for the next cost review.\n\nDecisions\n\nThe team will document deployment checks in the shared knowledge base. Each project owner will keep task dates up to date.',author:'Priya Patel'}];
export default function Home(){
 const [view,setView]=useState('Overview'),[projects,setProjects]=useState(initialProjects),[tasks,setTasks]=useState(initialTasks),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[modal,setModal]=useState(''),[detail,setDetail]=useState<typeof initialProjects[number]|null>(null),[notice,setNotice]=useState('');
 const [formError,setFormError]=useState('');
 const [knowledge,setKnowledge]=useState(initialKnowledge),[article,setArticle]=useState<typeof initialKnowledge[number]|null>(null),[editing,setEditing]=useState<typeof initialKnowledge[number]|null>(null);
 const navigate=(name:string)=>{setView(name);setQuery('');setFilter('All');};
 useEffect(()=>{
 const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;
 if(!context?.registerTool)return;
 const lifecycle=new AbortController();
 try{Promise.resolve(context.registerTool({name:'navigate_workspace',description:'Open a Cloud Team workspace view. Does not create or change records.',inputSchema:{type:'object',properties:{view:{type:'string',enum:nav.map(([name])=>name)}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{
 if(!input||typeof input!=='object'||!('view' in input)||!nav.some(([name])=>name===(input as {view:unknown}).view))throw new Error('Choose a supported workspace view');
 const target=(input as {view:string}).view;
 setView(target);setQuery('');setFilter('All');return {requestedView:target};
 }},{signal:lifecycle.signal})).catch(()=>{});}catch{}
 return ()=>lifecycle.abort();
 },[]);
 const create=(event:React.SyntheticEvent<HTMLFormElement>)=>{
 event.preventDefault();const data=new FormData(event.currentTarget);const name=(data.get('name') as string || '').trim();if(!name)return;const id=crypto.randomUUID();
 if(modal==='project')setProjects(addItem(projects,{id,name,description:(data.get('description') as string || 'Ready to get started.'),status:'On track',progress:0,team:'Platform',due:'Not set',color:'purple'}));
 else if(modal==='article'){
 const changes={name,category:data.get('category') as string,body:(data.get('body') as string).trim(),author:'Alex Morgan'};
 if(!changes.body)return;
 if(editing)setKnowledge(updateItem(knowledge,editing.id,changes));else setKnowledge(addItem(knowledge,{id,...changes}));setEditing(null);
 }else {const date=data.get('date') as string,start=data.get('start') as string;try{validateDates(start,date);}catch(e){setFormError(e instanceof Error?e.message:'Check the dates.');return;}setTasks(addItem(tasks,{id,name,projectId:data.get('projectId') as string,start,phase:data.get('phase') as string,date,status:'To do',priority:'Medium',owner:data.get('owner') as string,due:date||'Not set'}));}
 setNotice(`${modal==='article'?'Knowledge article':modal==='project'?'Project':'Task'} saved for this session.`);setModal('');
 };
 const selectedTasks=detail?projectTasks(tasks,detail.id):[];
 const visibleKnowledge=knowledge.filter(k=>(k.name+' '+k.body).toLowerCase().includes(query.trim().toLowerCase())&&(filter==='All'||k.category===filter));
 const visibleProjects=filterItems(projects,query,filter),visibleTasks=filterItems(tasks,query,filter);
 return <SidebarProvider><Sidebar className="app-sidebar"><SidebarHeader><div className="brand"><span className="brand-icon"><Cloud size={25}/></span> cloudteam<span className="brand-dot">.</span></div><div className="workspace"><span className="workspace-icon">C</span><div><strong>Cloud workspace</strong><small>Engineering team</small></div><ChevronDown size={16}/></div></SidebarHeader><SidebarContent><p className="nav-label">WORKSPACE</p><SidebarMenu>{nav.map(([name,Icon])=><SidebarMenuItem key={name}><SidebarMenuButton isActive={view===name||(name==='Projects'&&view==='Project workspace')} onClick={()=>navigate(name)} className="nav-button"><Icon/><span>{name}</span>{name==='Tasks'&&<span className="nav-count">{tasks.filter(t=>t.status!=='Done').length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-note"><span className="status-dot"/> All systems operational<small>Sample infrastructure status</small></div></SidebarContent><SidebarFooter><div className="demo-note"><Layers size={18}/><strong>Demo workspace</strong><p>Explore with sample data.<br/>Changes last for this session.</p></div><div className="profile"><span className="avatar">AM</span><div><strong>Alex Morgan</strong><small>Workspace admin</small></div></div></SidebarFooter></Sidebar><main className="main"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>Workspace</span><span>/</span><strong>{view}</strong></div><span className="sample-badge">SAMPLE DATA</span></header><div className="content"><div className="page-heading"><div><div className="eyebrow">YOUR WORKSPACE, CONNECTED</div><h1>{view==='Overview'?'Team overview':view==='Project workspace'?detail?.name:view==='Knowledge'?'Knowledge hub':view}</h1><p>{view==='Overview'?'A little clarity for everything your team is building.':({Projects:'Keep every initiative moving in the right direction.',Tasks:'Turn today’s priorities into progress.',Team:'The people behind your cloud.',Knowledge:'Shared knowledge. Fewer repeat questions.','Project workspace':'Tasks, owners and the timeline — together in one place.',Reports:'A closer look at your team and infrastructure.','Cloud resources':'One place to understand your infrastructure.'} as Record<string,string>)[view]}</p></div><button className="primary" onClick={()=>{setEditing(null);setModal(view==='Knowledge'?'article':view==='Tasks'||view==='Project workspace'?'task':'project')}}><Plus size={17}/>{view==='Knowledge'?'New article':view==='Tasks'||view==='Project workspace'?'Create task':'Create project'}</button></div>{notice&&<output className="notice">{notice}<button aria-label="Dismiss message" onClick={()=>setNotice('')}>×</button></output>}
{view==='Overview'&&<><div className="welcome-strip"><span className="welcome-icon"><Activity size={20}/></span><div><strong>Good things are moving.</strong><span> Your team has completed 24 tasks this week.</span></div><span className="week-pill">Week 37</span></div><div className="stats">{([[FolderKanban,'Active projects',String(projects.length),'Across 3 teams'],[Users,'Team members','4','All members active'],[Check,'Open tasks',String(tasks.filter(t=>t.status!=='Done').length),'Keep the momentum going'],[Cloud,'Monthly cloud spend','$2,000','12.4% below last month']] as const).map(([Icon,label,value,foot])=><section className="stat" key={label}><div><span>{label}</span><Icon size={18}/></div><strong>{value}</strong><small><span className="green">↗</span> {foot}</small></section>)}</div><div className="section-heading"><h2>Active projects <span>{projects.length}</span></h2><button className="text-button" onClick={()=>navigate('Projects')}>All projects <ArrowRight size={15}/></button></div></>}
{(view==='Overview'||view==='Projects')&&<>{view==='Projects'&&<div className="toolbar"><label className="search"><Search size={17}/><input aria-label="Search projects" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects…"/></label><div className="filter-buttons">{['All','On track','At risk'].map(s=><button className={filter===s?'selected':''} onClick={()=>setFilter(s)} key={s}>{s}</button>)}</div></div>}<div className="project-grid">{(view==='Overview'?projects.slice(0,3):visibleProjects).map((p:typeof initialProjects[number])=><button className="project-card" key={p.id} onClick={()=>{setDetail(p);navigate('Project workspace')}}><div className="card-top"><span className={'project-icon '+p.color}><FolderKanban size={21}/></span><span className={'badge '+(p.status==='At risk'?'amber':'green-badge')}>• {p.status}</span></div><h3>{p.name}</h3><p>{p.description}</p><div className="progress-label"><span>Progress</span><strong>{p.progress}%</strong></div><Progress value={p.progress} aria-label={`${p.name} progress`}/><div className="project-footer"><div className="avatar-stack"><span className="avatar small">AM</span><span className="avatar small blue">SC</span><span className="avatar small pink">JW</span></div><span><Clock size={13}/> {p.due}</span></div></button>)}</div>{visibleProjects.length===0&&<p className="empty">No projects match your search.</p>}</>}
{view==='Overview'&&<div className="lower-grid"><section className="panel"><div className="panel-heading"><div><h2>Your priorities</h2><p>A clear focus for the days ahead.</p></div><button className="text-button" onClick={()=>navigate('Tasks')}>View tasks <ArrowRight size={15}/></button></div>{tasks.slice(0,4).map(t=><div className="task-row" key={t.id}><button className={'complete '+(t.status==='Done'?'done':'')} disabled={t.status==='Done'} aria-label={`Complete ${t.name}`} onClick={()=>setTasks(completeTask(tasks,t.id))}>{t.status==='Done'&&<Check size={13}/>}</button><div><strong className={t.status==='Done'?'struck':''}>{t.name}</strong><small>{t.owner} <span>·</span> {t.due}</small></div><span className={'priority '+(t.priority==='High'?'high':'')}>{t.priority}</span></div>)}</section><section className="panel"><div className="panel-heading"><div><h2>Team workload</h2><p>Room to do great work.</p></div><Users size={18}/></div>{members.map(([name,_role,initial,load],i)=><div className="workload" key={name}><span className={'avatar '+(['','blue','pink','orange'][i])}>{initial}</span><div><div><strong>{name}</strong><span>{load}%</span></div><Progress value={load} aria-label={`${name} workload`} className={load>85?'busy':''}/></div></div>)}<button className="team-link" onClick={()=>navigate('Team')}>Meet your team <ArrowUpRight size={15}/></button></section></div>}
{view==='Tasks'&&<><div className="toolbar"><label className="search"><Search size={17}/><input aria-label="Search tasks" placeholder="Search tasks…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="filter-buttons">{['All','To do','In progress','Done'].map(s=><button key={s} className={filter===s?'selected':''} onClick={()=>setFilter(s)}>{s}</button>)}</div></div><div className="kanban">{['To do','In progress','Done'].map(status=><section className="kanban-column" key={status}><h2>{status}<span>{visibleTasks.filter((t:typeof initialTasks[number])=>t.status===status).length}</span></h2>{visibleTasks.filter((t:typeof initialTasks[number])=>t.status===status).map((t:typeof initialTasks[number])=><article className="task-card" key={t.id}><span className={'priority '+(t.priority==='High'?'high':'')}>{t.priority}</span><h3>{t.name}</h3><p>{t.owner}</p><div><span>{t.due}</span>{status!=='Done'&&<button className="text-button" onClick={()=>setTasks(completeTask(tasks,t.id))}><Check size={14}/> Complete</button>}</div></article>)}{visibleTasks.filter((t:typeof initialTasks[number])=>t.status===status).length===0&&<p className="empty">No tasks here.</p>}</section>)}</div></>}
{view==='Team'&&<div className="team-grid">{members.map(([name,role,initial,load],i)=><section className="panel member" key={name}><span className={'avatar large '+['','blue','pink','orange'][i]}>{initial}</span><h2>{name}</h2><p>{role}</p><span className="badge green-badge">• Available</span><div className="progress-label"><span>Weekly capacity used</span><strong>{load}%</strong></div><Progress value={load} aria-label={`${name} workload`}/></section>)}</div>}
{(view==='Cloud resources'||view==='Reports')&&<><div className="resource-banner"><span className="project-icon purple"><Cloud size={28}/></span><div><h2>{view==='Reports'?'Cloud spend overview':'Infrastructure at a glance'}</h2><p>September 2026 · Sample cloud inventory</p></div><strong>$2,000<small>/ month</small></strong></div>{view==='Reports'&&<section className="panel report"><h2>Spend by provider</h2>{[['AWS',1158],['Google Cloud',628],['Azure',214]].map(([name,amount])=><div key={name}><div className="progress-label"><strong>{name}</strong><span>${amount}</span></div><Progress value={Number(amount)/20} aria-label={`${name} share of spend`}/></div>)}</section>}<section className="panel resource-table"><Table><TableHeader><TableRow>{['Resource','Provider','Type','Status','Monthly cost'].map(s=><TableHead key={s}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{resources.map(r=><TableRow key={r[0]}>{r.map((v,i)=><TableCell key={i}>{i===3?<span className={'badge '+(v==='Healthy'?'green-badge':'amber')}>{v}</span>:v}</TableCell>)}</TableRow>)}</TableBody></Table></section></>}

{view==='Project workspace'&&detail&&<><button className="text-button back-link" onClick={()=>navigate('Projects')}>← All projects</button><div className="project-summary"><span className={'project-icon '+detail.color}><FolderKanban size={23}/></span><div><h2>{detail.team}</h2><p>{detail.description}</p></div><span className={'badge '+(detail.status==='At risk'?'amber':'green-badge')}>{detail.status}</span><div className="project-completion"><strong>{selectedTasks.filter((t:typeof initialTasks[number])=>t.status==='Done').length} / {selectedTasks.length}</strong><span>tasks complete</span></div></div><ProjectGantt tasks={selectedTasks} onAdd={()=>{setFormError('');setEditing(null);setModal('task')}} onUpdate={(id,changes)=>setTasks(updateItem(tasks,id,changes))}/></>}
{view==='Knowledge'&&<><div className="knowledge-banner"><span className="project-icon purple"><BookOpen size={26}/></span><div><h2>A home for what your team knows</h2><p>Runbooks, onboarding, guides and decisions, all in one place.</p></div><span>{knowledge.length} articles</span></div><div className="toolbar"><label className="search"><Search size={17}/><input aria-label="Search knowledge" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search titles and content…"/></label><div className="filter-buttons">{['All','Guides','Runbooks','Onboarding','Meeting notes'].map(c=><button key={c} className={filter===c?'selected':''} onClick={()=>setFilter(c)}>{c}</button>)}</div></div><div className="knowledge-grid">{visibleKnowledge.map(k=><button className="knowledge-card" key={k.id} onClick={()=>setArticle(k)}><div><span className="project-icon purple"><FileText size={20}/></span><span className="badge">{k.category}</span></div><h2>{k.name}</h2><p>{k.body.slice(0,145)}…</p><footer><span>{k.author}</span><span className="text-button">Read article <ArrowUpRight size={14}/></span></footer></button>)}</div>{visibleKnowledge.length===0&&<p className="empty">No articles found. Try another search or create a new article.</p>}</>}
<footer className="page-footer"><span><span className="status-dot"/> Cloud Team Management</span><span>Demo workspace · Session-only changes</span></footer></div></main><Dialog open={!!modal} onOpenChange={open=>{if(!open){setModal('');setFormError('')}}}><DialogContent><DialogHeader><DialogTitle>{editing?'Edit':'Create'} {modal}</DialogTitle><DialogDescription>Add a {modal} to this demo session.</DialogDescription></DialogHeader><form className="create-form" onSubmit={create}><label>Name<input name="name" required maxLength={100} defaultValue={editing?.name||''} placeholder={modal==='project'?'e.g. Platform modernization':modal==='article'?'e.g. Incident response guide':'e.g. Review deployment checklist'}/></label>{modal==='project'&&<label>Description<textarea name="description" maxLength={240}/></label>}{modal==='task'&&<><label>Project<NativeSelect name="projectId" defaultValue={view==='Project workspace'?detail?.id:projects[0]?.id} required>{projects.map(p=><NativeSelectOption key={p.id} value={p.id}>{p.name}</NativeSelectOption>)}</NativeSelect></label><div className="form-columns"><label>Owner<NativeSelect name="owner">{members.map(([name])=><NativeSelectOption key={name}>{name}</NativeSelectOption>)}</NativeSelect></label><label>Start date<input type="date" name="start"/></label><label>Finish date<input type="date" name="date"/></label><label>Phase<NativeSelect name="phase">{['Planning','Development','Launch'].map(p=><NativeSelectOption key={p}>{p}</NativeSelectOption>)}</NativeSelect></label></div></>}{modal==='article'&&<><label>Category<NativeSelect name="category" defaultValue={editing?.category||'Guides'}>{['Guides','Runbooks','Onboarding','Meeting notes'].map(c=><NativeSelectOption key={c}>{c}</NativeSelectOption>)}</NativeSelect></label><label>Content<textarea className="article-editor" name="body" required maxLength={12000} defaultValue={editing?.body||''} placeholder="Write the steps, decisions or knowledge your team needs…"/></label></>}{formError&&<p className="form-error" role="alert">{formError}</p>}<button className="primary" type="submit"><Plus size={16}/>{editing?'Save changes':`Create ${modal}`}</button></form></DialogContent></Dialog><Dialog open={!!article} onOpenChange={open=>{if(!open)setArticle(null)}}><DialogContent className="article-dialog"><DialogHeader><span className="eyebrow">{article?.category}</span><DialogTitle>{article?.name}</DialogTitle><DialogDescription>By {article?.author} · Demo knowledge base</DialogDescription></DialogHeader><div className="article-body">{article?.body}</div><button className="primary" onClick={()=>{setEditing(article);setArticle(null);setModal('article')}}>Edit article</button></DialogContent></Dialog></SidebarProvider>
}
